FROM tensorflow/tensorflow:1.15.0-py3

# Install google utils for accessing GCP per https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | \
    tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
    apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && \
    apt-get update -y && \
    apt-get install google-cloud-sdk -y

# Install wget (to make life easier below) and editors (to allow people to edit the files inside the container)
RUN apt-get update -y && \
    apt-get install -y \
    wget \
    vim \
    nano \
    git

# Install object detection api dependencies
RUN apt-get install -y \
    build-essential \
    protobuf-compiler \
    python-pil \
    python-lxml \
    python3-dev

# Install remaining python dependencies
COPY requirements.txt .
RUN pip install --upgrade -r requirements.txt


# Install remaining python dependencies
ENV TZ=America/Nome
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt-get install -y python3-tk

# Get the tensorflow models research directory, and move it into tensorflow
# Froze the codebase before Oct 15,2020 https://github.com/tensorflow/models/commit/ea30986e0cc14b1872cb6a4b9192f18ad73208f7
RUN git clone --progress https://github.com/tensorflow/models.git /tensorflow/models && \
    cd /tensorflow/models && \
    git checkout ea30986e0cc14b1872cb6a4b9192f18ad73208f7

# # Run protoc on the object detection repo
RUN cd /tensorflow/models/research && \
    protoc object_detection/protos/*.proto --python_out=.
# Set the PYTHONPATH to finish installing the API
ENV PYTHONPATH $PYTHONPATH:/tensorflow/models/research:/tensorflow/models/research/slim

# Install pycocoapi for instance segmentation utils
# Froze the codebase before Feb 20, 2020, https://github.com/cocodataset/cocoapi/commit/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9
RUN git clone https://github.com/cocodataset/cocoapi.git && \
    cd cocoapi/PythonAPI && \
    git checkout 8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9 && \
    python setup.py build_ext install && \
    make && \
    make install

# Training School Detector
COPY aiaia_detector/ /tensorflow/school_detector/
RUN chmod +x /tensorflow/aiaia_detector/model_main.py

WORKDIR /mnt/data
