apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "faster-rcnn-resnet101-serengeti-wildlife"
  namespace: "kubeflow"
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          serviceAccountName: kf-user
          containers:
          - name: tensorflow
            image: aiaiatrain.azurecr.io/aiaia-tf1.15-frozen_graph
            command:
              - "python"
              - "/tensorflow/aiaia_detector/model_main.py"
              - "--model_dir=https://aiaiatrain.blob.core.windows.net/gcsprocessedtraining/model_outputs_tf1/rcnn_resnet101_serengeti_wildlife"
              - "--pipeline_config_path=https://aiaiatrain.blob.core.windows.net/gcsprocessedtraining/model_configs_tf1/configs/rcnn_resnet101_serengeti_wildlife.config"
              - "--num_train_steps=50000"
              - "--sample_1_of_n_eval_examples=1"
              - "--input_type=image_tensor"
              - "--output_directory=https://aiaiatrain.blob.core.windows.net/gcsprocessedtraining/export_outputs_tf1/rcnn_resnet101_serengeti_wildlife"
            resources:
              limits:
                nvidia.com/gpu: 1
            restartPolicy: Never
            tolerations:
              - key: "nvidia.com/gpu"
                operator: "Equal"
                value: "present"
                effect: "NoSchedule"
          volumes:
          - name: training
            persistentVolumeClaim:
              claimName: pvc