apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: managed-premium
  resources:
    requests:
      storage: 300Gi
