version: '3'
services:
  aiaia_tf:
    image: aiaiatrain.azurecr.io/aiaia_tfrecord_eval_cpu # change to cpu or gpu depending on what you are using for evaluation
    build:
      context: .
      dockerfile: Dockerfile-data-eval-cpu # change to cpu or gpu depending on what you are using for evaluation
    ports:
      - "8888:8888"
    user: ${USERID}
    volumes:
        - ./:/AIAIA/
    working_dir: /AIAIA/