apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "aiaia-classifier-v1"
  namespace: "kubeflow"
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          serviceAccountName: kf-user
          containers:
          - name: tensorflow
            image: gcr.io/bp-padang/aiaia-classifier:v1.2-xception-binary
            command:
              - "python"
              - "/opt/model.py"
              - "--n_classes=2"
              - "--class_names=not_object,object"
              - "--countries=aiaia"
              - "--tf_dense_size=153"
              - "--tf_dense_dropout_rate=0.34"
              - "--tf_learning_rate=0.00027"
              - "--tf_optimizer=adam"
              - "--tf_train_data_dir=gs://aiaia_od/training_data_aiaia_p400/classification_training_tfrecords/"
              - "--tf_val_data_dir=gs://aiaia_od/training_data_aiaia_p400/classification_training_tfrecords/"
              - "--tf_model_dir=gs://aiaia_od/classification_model_outputs/"
              - "--local_dataset_dirs=/ml/data"
              - "--tf_steps_per_checkpoint=100"
              - "--tf_steps_per_summary=500"
              - "--tf_train_steps=6000"
              - "--tf_batch_size=8"
              - "--gcs_destination_blob=classification_model_outputs"
              - "--gcs_destination_bucket=aiaia_od"
              - "--model_gs_upload_id=v1"
              - "--model_id=abc"
            resources:
              limits:
                nvidia.com/gpu: 1
            restartPolicy: Never
            tolerations:
              - key: "nvidia.com/gpu"
                operator: "Equal"
                value: "present"
                effect: "NoSchedule"
            nodeSelector:
              cloud.google.com/gke-accelerator: nvidia-tesla-k80
