apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "rcnn-resnet101-serengeti-huma-activities"
  namespace: "kubeflow"
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          serviceAccountName: kf-user
          containers:
          - name: tensorflow
            image: gcr.io/bp-padang/aiaia:v1.1-tf1.15-gpu
            command:
              - "python"
              - "/tensorflow/aiaia_detector/model_main.py"
              - "--model_dir=gs://aiaia_od/model_outputs_tf1/rcnn_resnet101_serengeti_human_activities_v1"
              - "--pipeline_config_path=gs://aiaia_od/model_configs_tf1/configs/rcnn_resnet101_serengeti_human_activities.config"
              - "--num_train_steps=50000"
              - "--sample_1_of_n_eval_examples=1"
              - "--input_type=encoded_image_string_tensor"
              - "--output_directory=gs://aiaia_od/export_outputs_tf1/rcnn_resnet101_serengeti_human_activities_v1_tfs_v2"
            resources:
              limits:
                nvidia.com/gpu: 1
            restartPolicy: Never
            tolerations:
              - key: "nvidia.com/gpu"
                operator: "Equal"
                value: "present"
                effect: "NoSchedule"
            nodeSelector:
              cloud.google.com/gke-accelerator: nvidia-tesla-k80
