FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04

RUN apt-get update
RUN apt-get install --no-install-recommends --no-install-suggests -y curl
RUN apt-get install unzip
RUN apt -y install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
RUN wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
RUN tar -xf Python-3.7.2.tar.xz && cd Python-3.7.2 && ./configure &&  make install

RUN apt-get -y install \
    protobuf-compiler \
    libxml2-dev \
    libxslt-dev

# # # # Install remaining python dependencies
RUN pip3 install --upgrade pip setuptools==49.6.0 wheel

RUN pip3 install \
    tensorflow-gpu==1.15.0 \
    Cython==0.28.2 \
    lxml==4.2.1 \
    contextlib2 \
    pillow==6.1.0 \
    lxml==4.2.1 \
    scipy==1.3.1 \
    tf-slim==1.1.0 \
    protobuf==3.7 \
    numpyencoder \
    click \
    matplotlib\
    joblib \
    tqdm


RUN apt-get -y install git

RUN git clone --progress https://github.com/tensorflow/models.git /tensorflow/models && \
    cd /tensorflow/models && \
    git checkout ea30986e0cc14b1872cb6a4b9192f18ad73208f7

# # Run protoc on the object detection repo
RUN cd /tensorflow/models/research && \
    protoc object_detection/protos/*.proto --python_out=.
# Set the PYTHONPATH to finish installing the API
ENV PYTHONPATH $PYTHONPATH:/tensorflow/models/research:/tensorflow/models/research/slim

ENV PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

WORKDIR /mnt/data
